# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build package and demo app"
  lane :build do
    build_app(
      project: "GentleNetworkingDemo.xcodeproj",
      scheme: "GentleNetworkingDemo",
      configuration: "Debug",
      skip_package_ipa: true,   # important: avoids IPA packaging
      destination: "generic/platform=iOS Simulator"
    )
  end

lane :package_tests do
    repo_root = File.expand_path("../../..", __dir__) # fastlane → repo root

    Dir.chdir(repo_root) do
      sh <<~CMD
        set -euo pipefail
        rm -rf TestResults.xcresult
        xcodebuild test \
          -scheme GentleNetworking \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone 17" \
          -enableCodeCoverage YES \
          -resultBundlePath TestResults.xcresult
      CMD
    end
  end
end
